### ISSUE TITLE
Production Login is broken

### ISSUE THREAD

**Issue by mathewmorris** [mathewmorris/magic-vault#16]
When I try to log in, I get an error in the client regardless of the provider used: 

![Image](https://github.com/user-attachments/assets/4181d9e4-a932-45cf-8b45-779876df4bca)

**Comment by mathewmorris** [comment]
Getting an error in the runtime logs for production

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error redirect_uri_mismatch {
  message: 'redirect_uri_mismatch',
  stack: 'Error: redirect_uri_mismatch\n' +
    '    at oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:39:19)\n' +
    '    at Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:39)\n' +
    '    at AuthHandler (/var/task/node_modules/next-auth/core/index.js:208:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async NextAuthApiHandler (/var/task/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async NextAuth._args$ (/var/task/node_modules/next-auth/next/index.js:108:14)',
  name: 'Error'
}
```

interesting since the provider handles everything to do with the redirect_uri. Might be an issue with the `GITHUB_ID` OR `GITHUB_SECRET` secrets for production build.

**Comment by mathewmorris** [comment]
Discord runtime error:

```
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
Invalid `prisma.account.findUnique()` invocation:


Can't reach database server at `198.58.122.136:5432`

Please make sure your database server is running at `198.58.122.136:5432`. {
  message: '\n' +
    'Invalid `prisma.account.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    "Can't reach database server at `198.58.122.136:5432`\n" +
    '\n' +
    'Please make sure your database server is running at `198.58.122.136:5432`.',
  stack: 'PrismaClientInitializationError: \n' +
    'Invalid `prisma.account.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    "Can't reach database server at `198.58.122.136:5432`\n" +
    '\n' +
    'Please make sure your database server is running at `198.58.122.136:5432`.\n' +
    '    at _n.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:121:8049)\n' +
    '    at _n.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:121:7057)\n' +
    '    at _n.request (/var/task/node_modules/@prisma/client/runtime/library.js:121:6741)\n' +
    '    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:130:9355)\n' +
    '    at async getUserByAccount (/var/task/node_modules/@next-auth/prisma-adapter/dist/index.js:211:29)',
  name: 'PrismaClientInitializationError'
}
```

So definitely a database issue.

**Comment by mathewmorris** [comment]
So, my database is up, now I need to figure out how to run migrations with each deployment.
